// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0n9IkiO5Xm-SdFS8ZGNHBf0RDVs65S7A',
    appId: '1:42353337294:web:09bfadcad07cce51d4019f',
    messagingSenderId: '42353337294',
    projectId: 'the-aura-30e2a',
    authDomain: 'the-aura-30e2a.firebaseapp.com',
    storageBucket: 'the-aura-30e2a.firebasestorage.app',
    measurementId: 'G-TR3MZP5ZFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0jqndhSAspSwD-n6UWpROqsvB3KbZyJE',
    appId: '1:42353337294:android:8d6bffac8d32e0e0d4019f',
    messagingSenderId: '42353337294',
    projectId: 'the-aura-30e2a',
    storageBucket: 'the-aura-30e2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcItXljWZVcKJb27Oy6wc87mbCNHXnHS8',
    appId: '1:42353337294:ios:82ba1c888e0764c1d4019f',
    messagingSenderId: '42353337294',
    projectId: 'the-aura-30e2a',
    storageBucket: 'the-aura-30e2a.firebasestorage.app',
    iosBundleId: 'com.example.theAura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcItXljWZVcKJb27Oy6wc87mbCNHXnHS8',
    appId: '1:42353337294:ios:82ba1c888e0764c1d4019f',
    messagingSenderId: '42353337294',
    projectId: 'the-aura-30e2a',
    storageBucket: 'the-aura-30e2a.firebasestorage.app',
    iosBundleId: 'com.example.theAura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0n9IkiO5Xm-SdFS8ZGNHBf0RDVs65S7A',
    appId: '1:42353337294:web:912d974dab9e6b39d4019f',
    messagingSenderId: '42353337294',
    projectId: 'the-aura-30e2a',
    authDomain: 'the-aura-30e2a.firebaseapp.com',
    storageBucket: 'the-aura-30e2a.firebasestorage.app',
    measurementId: 'G-YD8274FRYX',
  );
}
